# Check the versions of libraries

# Python version
import sys
print('Python: {}'.format(sys.version))
# numpy
import numpy
print('numpy: {}'.format(numpy.__version__))
# pandas
import pandas
print('pandas: {}'.format(pandas.__version__))
# scipy
import scipy
print('scipy: {}'.format(scipy.__version__))
# matplotlib
import matplotlib
print('matplotlib: {}'.format(matplotlib.__version__))
# seaborn
import seaborn
print('seaborn: {}'.format(seaborn.__version__))
# plotly
import plotly
print('plotly: {}'.format(plotly.__version__))
# scikit-learn
import sklearn
print('sklearn: {}'.format(sklearn.__version__))
# tensorflow
import tensorflow
print('tensorflow: {}'.format(tensorflow.__version__))
# torch
import torch
print('torch: {}'.format(torch.__version__))
# nltk
import nltk
print('nltk: {}'.format(nltk.__version__))
# spacy
import spacy
print('spacy: {}'.format(spacy.__version__))
# gensim
import gensim
print('gensim: {}'.format(gensim.__version__))
